name: "RAG Smoke (Phase-10)"

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  rag-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Echo"
        run: echo "RAG smoke skeleton works"