name: "RAG Smoke (Phase-10)"

on:
  push:
    branches: [ "main", "master", "feature/**" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  rag-smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: "Install deps"
        shell: bash
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: "1"
          PIP_NO_INPUT: "1"
          PIP_DEFAULT_TIMEOUT: "100"
        run: |
          python -m pip install -U pip wheel setuptools
          # Torch (CPU) – стабильные колёса для runner'а
          pip install --extra-index-url https://download.pytorch.org/whl/cpu "torch==2.8.0"
          # Основные зависимости проекта
          pip install --prefer-binary -r requirements.txt
          pip install --prefer-binary -r requirements-memory.txt || true
          # Для RAG/ингеста и загрузки моделей
          pip install --prefer-binary "chromadb==0.5.3" "duckdb==0.10.2" \
                                   "FlagEmbedding>=1.2.10" "python-multipart>=0.0.9" \
                                   "huggingface_hub[cli]>=0.23"

      - name: "Download embeddings (bge-m3)"
        shell: bash
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}  # можно без токена; с токеном быстрее/стабильнее
        run: |
          set -e
          mkdir -p "$GITHUB_WORKSPACE/models/bge-m3" "$GITHUB_WORKSPACE/storage/chroma"
          huggingface-cli download --repo-type model BAAI/bge-m3 \
            --local-dir "$GITHUB_WORKSPACE/models/bge-m3" \
            --local-dir-use-symlinks False
          ls -lh "$GITHUB_WORKSPACE/models/bge-m3" | head -n 20

      - name: "Preflight: load BGE-M3 locally"
        shell: bash
        run: |
          python - <<'PY'
          import os
          from pathlib import Path
          from FlagEmbedding import BGEM3FlagModel

          ws = Path(os.environ.get("GITHUB_WORKSPACE", "."))
          p = ws / "models" / "bge-m3"

          print("model_dir:", p)
          print("exists:", p.exists())
          print("files:", sum(1 for _ in p.rglob('*')))

          _ = BGEM3FlagModel(p.as_posix(), use_fp16=False, device="cpu")
          print("✓ Model loaded OK")
          PY

      - name: "Write CI .env"
        shell: bash
        run: |
          cat > .env <<'ENV'
          ENABLE_MEMORY=true
          AIR4_ENABLE_MEMORY=true
          AIR4_MEMORY_BACKEND=chroma
          AIR4_CHROMA_COLLECTION=air4_memory
          CHROMA_DIR=$GITHUB_WORKSPACE/storage/chroma
          AIR4_EMBED_MODEL_PATH=$GITHUB_WORKSPACE/models/bge-m3
          AIR4_OFFLINE=0
          ENV
          # Нормализуем перевод строк и покажем первые строки
          sed -i -e 's/\r$//' .env || true
          echo "---- .env (first lines) ----"
          sed -n '1,80p' .env

      - name: "Start API (bg)"
        shell: bash
        run: |
          set -e
          mkdir -p "$GITHUB_WORKSPACE/storage/chroma"
          uvicorn backend.app.main:app \
            --host 127.0.0.1 \
            --port 8000 \
            --log-level debug \
            --env-file .env \
            > server.log 2>&1 &
          echo $! > .uvicorn.pid

          # Ждём готовности API
          for i in {1..30}; do
            curl -fsS http://127.0.0.1:8000/health && break || sleep 1
          done

          echo "---- /health after boot ----"
          curl -sS http://127.0.0.1:8000/health || true

      - name: "Health check"
        shell: bash
        run: curl -fsS http://127.0.0.1:8000/health

      - name: "Guard: ensure Chroma + embeddings are active"
        shell: bash
        run: |
          set -e
          out="$(curl -fsS http://127.0.0.1:8000/health || true)"
          echo "$out"
          echo "---- quick env check ----"
          python -V
          pip show chromadb duckdb FlagEmbedding || true

          # Мини-валидация .env для отладки
          echo "---- .env (first lines) ----"
          sed -n '1,120p' .env

          if echo "$out" | grep -q '"memory_backend":"chroma"'; then
            echo "✓ Chroma backend active"
          else
            echo "Memory backend is NOT 'chroma' (embeddings init failed?)"
            echo "---- tail server.log ----"
            tail -n 200 server.log || true
            exit 2
          fi

      - name: "Sanity: one ingest call (debug)"
        shell: bash
        run: |
          set -e
          echo "Trying single ingest…"
          curl -sS -o /tmp/ingest_resp.json -w "\nHTTP:%{http_code}\n" \
            -F "file=@tests/rag_corpus/docs/noise_finance.txt" \
            http://127.0.0.1:8000/ingest/file || true
          echo "--- ingest response (first 400 chars) ---"
          head -c 400 /tmp/ingest_resp.json || true
          echo
          if jq . /tmp/ingest_resp.json >/dev/null 2>&1; then
            echo "OK: JSON received"
          else
            echo "ERR: not a JSON, see above"; exit 5
          fi

      - name: "Run smoke"
        shell: bash
        run: |
          set -e
          export K=6
          export MMR=0.4
          export HYDE=2
          export THRESHOLD=0.30
          echo "CI params: K=$K MMR=$MMR HYDE=$HYDE THRESHOLD=$THRESHOLD"
          bash scripts/smoke_phase10_rag.sh

      - name: "Upload smoke log (artifact)"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: "smoke-log"
          path: |
            .smoke.log
            .smoke_phase10_step2.log
            server.log
          if-no-files-found: ignore

      - name: "Teardown"
        if: always()
        shell: bash
        run: |
          if [ -f .uvicorn.pid ]; then
            kill "$(cat .uvicorn.pid)" 2>/dev/null || true
          fi