name: RAG Smoke (Phase-10)

on:
  push:
    branches: [ main, master, feature/** ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rag-smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-memory.txt || true
          pip install uvicorn || true

      - name: Prepare folders
        run: |
          mkdir -p models/bge-m3 storage/chroma
          chmod +x scripts/*.sh || true

      - name: Download embeddings (bge-m3)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          bash scripts/setup_embeddings.sh
          ls -lh models/bge-m3 || true

      - name: Start API (bg)
        run: |
          uvicorn backend.app.main:app --host 127.0.0.1 --port 8000 &
          echo $! > .uvicorn.pid
          for i in {1..10}; do
            curl -fsS http://127.0.0.1:8000/health && break || sleep 1
          done

      - name: Health check
        run: curl -fsS http://127.0.0.1:8000/health

      - name: Run smoke
        run: bash scripts/smoke_phase10_rag.sh

      - name: Upload smoke log (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-log
          path: |
            .smoke.log
            .smoke_phase10_step2.log
          if-no-files-found: ignore

      - name: Teardown
        if: always()
        run: |
          if [ -f .uvicorn.pid ]; then kill $(cat .uvicorn.pid) || true; fi