name: RAG Smoke (Phase-10)

on:
  push:
    branches: [ main, master, feature/** ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rag-smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-memory.txt || true
          # гарантированно для BGE-M3
          pip install -U "torch>=2.3,<2.4" --index-url https://download.pytorch.org/whl/cpu
          pip install -U "sentence-transformers>=3.0.1" "FlagEmbedding>=1.2.10" "onnxruntime>=1.17.0"

      - name: Download embeddings (bge-m3)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          mkdir -p models/bge-m3 storage/chroma
          huggingface-cli download \
            --repo-type model BAAI/bge-m3 \
            --local-dir models/bge-m3 \
            --local-dir-use-symlinks False
          ls -lh models/bge-m3 | head -n 20

      - name: "Preflight: load BGE-M3 locally"
        run: |
          python - <<'PY'
          from pathlib import Path
          from FlagEmbedding import BGEM3FlagModel
          p = Path("models/bge-m3")
          print("files:", len(list(p.rglob('*'))))
          m = BGEM3FlagModel(str(p), use_fp16=False, device="cpu")
          out = m.encode(["hello world"])
          print("vec dims:", len(out["dense_vecs"][0]))
          PY

      - name: Write CI .env
        run: |
          cat > .env <<'EOF'
          AIR4_EMBED_MODEL_PATH=models/bge-m3
          AIR4_CHROMA_COLLECTION=air4_memory
          AIR4_MEMORY_BACKEND=chroma
          CHROMA_DIR=storage/chroma
          AIR4_OFFLINE=1
          EOF
          cat .env

      - name: Start API (bg)
        run: |
          mkdir -p "$CHROMA_DIR"
          uvicorn backend.app.main:app \
            --host 127.0.0.1 --port 8000 --log-level debug >server.log 2>&1 &
          echo $! > .uvicorn.pid
          for i in {1..30}; do
            curl -fsS http://127.0.0.1:8000/health && break || sleep 1
          done
          echo "---- /health ----"
          curl -sS http://127.0.0.1:8000/health || true

      - name: Health check
        run: curl -fsS http://127.0.0.1:8000/health

      - name: "Guard: ensure Chroma + embeddings are active"
        run: |
          set -e
          resp=$(curl -sS http://127.0.0.1:8000/health)
          echo "$resp"
          echo "$resp" | grep '"memory_backend":"chroma"' || {
            echo "Memory backend is NOT 'chroma' (embeddings init failed?)."
            echo "---- tail server.log ----"
            tail -n 100 server.log || true
            exit 2
          }

      - name: "Sanity: one ingest call (debug)"
        run: |
          set -e
          echo "Trying single ingest…"
          curl -sS -o /tmp/ingest_resp.json -w "\nHTTP:%{http_code}\n" \
            -F "file=@tests/rag_corpus/docs/noise_finance.txt" \
            http://127.0.0.1:8000/ingest/file || true
          echo "--- ingest response (first 400 chars) ---"
          head -c 400 /tmp/ingest_resp.json || true
          echo
          echo "----------------------------------------"
          if jq . /tmp/ingest_resp.json >/dev/null 2>&1; then
            echo "OK: JSON received"
          else
            echo "ERR: not a JSON, see above"; exit 5
          fi

      - name: Run smoke
        run: bash scripts/smoke_phase10_rag.sh

      - name: Upload smoke log (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-log
          path: |
            .smoke.log
            .smoke_phase10_step2.log
            server.log
          if-no-files-found: ignore

      - name: Teardown
        if: always()
        run: |
          if [ -f .uvicorn.pid ]; then kill $(cat .uvicorn.pid) || true; fi