name: RAG Smoke (Phase-10)

on:
  push:
    branches: [ main, develop, feature/** ]
  pull_request:
    branches: [ main, develop ]

jobs:
  rag-smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      - name: Launch uvicorn
        run: |
          nohup uvicorn backend.app.main:app --host 127.0.0.1 --port 8000 > uvicorn.log 2>&1 &
          for i in {1..60}; do
            code=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:8000/health || true)
            if [ "$code" = "200" ]; then echo "API is up"; break; fi
            sleep 0.5
          done
          test "$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:8000/health)" = "200"

      - name: Ensure __routes is removed
        run: |
          code=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:8000/__routes || true)
          test "$code" = "404"

      - name: Add noise docs (idempotent)
        run: |
          mkdir -p tests/rag_corpus/docs/noise
          echo "CI noise document to validate retriever robustness." > tests/rag_corpus/docs/noise/ci_noise.txt

      - name: Run smoke script
        shell: bash
        run: |
          bash scripts/smoke_phase10_rag.sh | tee .smoke.log
          AVG=$(grep -Eo 'avg p@3[[:space:]]*=[[:space:]]*[0-9.]+' .smoke.log | tail -1 | sed -E 's/.*=[[:space:]]*([0-9.]+)/\1/')
          echo "avg p@3 = ${AVG}"
          awk -v a="$AVG" 'BEGIN{exit (a>=0.7)?0:1}'

      - name: Upload smoke log (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-log
          path: .smoke.log
