name: "RAG Smoke (Phase-10)"

on:
  push:
    branches: [ "main", "master", "feature/**" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  rag-smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: "Install deps"
        shell: bash
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: "1"
          PIP_NO_INPUT: "1"
          PIP_DEFAULT_TIMEOUT: "120"
        run: |
          python -m pip install -U pip wheel setuptools
          # CPU torch
          pip install --extra-index-url https://download.pytorch.org/whl/cpu "torch==2.8.0"
          # Основные зависимости проекта
          pip install --prefer-binary -r requirements.txt
          pip install --prefer-binary -r requirements-memory.txt || true
          # Для эмбеддингов/ингеста/вектора
          pip install --prefer-binary \
            "FlagEmbedding>=1.2.10" \
            "python-multipart>=0.0.9" \
            "chromadb==0.5.4" \
            "duckdb==1.0.0" \
            "uvicorn>=0.30" \
            "huggingface_hub[cli]>=0.23"

          python - <<'PY'
          import sys
          import importlib
          for m in ("chromadb","duckdb","FlagEmbedding","multipart"):
              try:
                  mod = importlib.import_module(m)
                  print(f"OK import {m}", getattr(mod, "__version__", ""))
              except Exception as e:
                  print("FAIL import", m, e); sys.exit(1)
          PY

      - name: "Download embeddings (bge-m3)"
        shell: bash
        env:
          HF_TOKEN: "${{ secrets.HF_TOKEN }}"
        run: |
          mkdir -p models/bge-m3 storage/chroma
          huggingface-cli download \
            --repo-type model BAAI/bge-m3 \
            --local-dir models/bge-m3 \
            --local-dir-use-symlinks False
          ls -lh models/bge-m3 | head -n 30

      - name: "Preflight: load BGE-M3 locally"
        shell: bash
        run: |
          cat > /tmp/_preflight.py <<'PY'
          from pathlib import Path
          from FlagEmbedding import BGEM3FlagModel
          p = Path("models/bge-m3")
          print("files:", len(list(p.rglob('*'))))
          _ = BGEM3FlagModel(p.as_posix(), use_fp16=False, device="cpu")
          print("OK: BGE-M3 loaded")
          PY
          python /tmp/_preflight.py

      - name: "Write CI .env"
        shell: bash
        run: |
          # Абсолютные пути — чтобы uvicorn/рабочая папка не мешали
          ROOT="${GITHUB_WORKSPACE}"
          EMB="${ROOT}/models/bge-m3"
          CHR="${ROOT}/storage/chroma"

          {
            echo 'ENABLE_MEMORY=true'
            echo 'AIR4_ENABLE_MEMORY=true'
            echo "AIR4_EMBED_MODEL_PATH=${EMB}"
            echo 'AIR4_MEMORY_BACKEND=chroma'
            echo 'AIR4_MEMORY_FORCE_FALLBACK=0'
            echo "AIR4_CHROMA_COLLECTION=air4_memory"
            echo "CHROMA_DIR=${CHR}"
            echo 'AIR4_OFFLINE=0'
            echo 'MODEL_NAME=llama3.1:8b'
            echo 'OLLAMA_BASE_URL=http://127.0.0.1:11434'
          } > .env

          echo "---- .env ----"
          sed -n '1,200p' .env

      - name: "Start API (bg)"
        shell: bash
        run: |
          set -e
          mkdir -p storage/chroma
          # Экспортируем .env в окружение и дополнительно передаём как --env-file
          set -a; source .env; set +a
          uvicorn backend.app.main:app \
            --host 127.0.0.1 \
            --port 8000 \
            --log-level debug \
            --env-file .env \
            > server.log 2>&1 &

          echo $! > .uvicorn.pid

          # Ждём ответа /health
          for i in {1..40}; do
            curl -fsS http://127.0.0.1:8000/health >/dev/null && break || sleep 1
          done
          echo "---- /health after boot ----"
          curl -sS http://127.0.0.1:8000/health || true

      - name: "Health check"
        shell: bash
        run: curl -fsS http://127.0.0.1:8000/health

      - name: "Guard: ensure Chroma + embeddings are active"
        shell: bash
        run: |
          set -e
          out="$(curl -fsS http://127.0.0.1:8000/health)"
          echo "$out"

          # допускаем 2 формата поля: top-level "memory_backend" и nested
          if echo "$out" | grep -q '"memory_backend":"chroma"'; then
            echo "✓ Chroma backend active"
          elif echo "$out" | grep -q '"backend":"chroma"'; then
            echo "✓ Chroma backend active (nested)"
          else
            echo "Memory backend is NOT 'chroma' (embeddings init failed?)"
            echo "---- quick env check ----"
            python -V
            pip show chromadb duckdb FlagEmbedding || true
            echo "---- tail server.log ----"
            tail -n 200 server.log || true
            exit 2
          fi

      - name: "Sanity: one ingest call (debug)"
        shell: bash
        run: |
          set -e
          echo "Trying single ingest…"
          curl -sS -o /tmp/ingest_resp.json -w "\nHTTP:%{http_code}\n" \
            -F "file=@tests/rag_corpus/docs/noise_finance.txt" \
            http://127.0.0.1:8000/ingest/file || true
          echo "--- ingest response (first 400 chars) ---"
          head -c 400 /tmp/ingest_resp.json || true
          echo
          if jq . /tmp/ingest_resp.json >/dev/null 2>&1; then
            echo "OK: JSON received"
          else
            echo "ERR: not a JSON, see above"; exit 5
          fi

      - name: "Run smoke"
        shell: bash
        env:
           K="6"
           MMR="0.4"
           HYDE="2"
           THRESHOLD="0.30"
        run: |
        echo "CI params: K=$K MMR=$MMR HYDE=$HYDE THRESHOLD=$THRESHOLD"
        bash scripts/smoke_phase10_rag.sh
        
      - name: "Upload smoke log (artifact)"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: "smoke-log"
          path: |
            .smoke.log
            .smoke_phase10_step2.log
            server.log
          if-no-files-found: ignore

      - name: "Teardown"
        if: always()
        shell: bash
        run: |
          if [ -f .uvicorn.pid ]; then kill "$(cat .uvicorn.pid)" || true; fi